### ISSUE TITLE
program esp8266 or arduino sheild?

### ISSUE THREAD

**Issue by DaneshX** [yaacov/ArduinoModbusSlaveTCP#1]
Hello
can i use this library for esp8266 stand alone or i should use it with arduino board?

**Comment by yaacov** [comment]
Hi,
I tested it only with esp8266 stand alone, I will be happy to know if you can run it on other platforms.

**Comment by DaneshX** [comment]
i plane to use it in real time program .... and how can i diagnose i have conection to modbus master(for example OPC) sometimes data qulity is "BAD" and how can i know it trough ESP?
thanks

**Comment by yaacov** [comment]
the esp is the controller you do not need to communicate trough it.
you will have a problem of bad quality signal in any solution that is not physical lines, if you need high availability you will need to use physical lines ( Ethernet, rs485, ... ).

**Comment by DaneshX** [comment]
sometimes its ok but sometimes its BAD and if i reset it ... its ok! its randomly and stuck in "BAD" Quality.... is there any way that i know when data is BAD and i reset esp?
thanks alot for your answers

**Comment by yaacov** [comment]
I do not have a good answer :-(
I will be very happy to know how you solved it (once you do).
I can think about many watch-dog like solutions, but I do not know what is best in your case.

**Comment by DaneshX** [comment]
i test watchdog but not works because ESP dosent stuck in program ... i can ping slave id ! but Data quality is Bad in OPC!!and i should reset  ESP to fix it!
do you use your code for real time working?

**Comment by yaacov** [comment]
no, i did not test this code in a real environment.
wifi for important data is problematic even when it works well :-)

**Comment by DaneshX** [comment]
mmm...but todaty Iot is Based on wifi:)

**Comment by yaacov** [comment]
I will be happy to know how you solved it, once you do. I'm sure you overlooked a solution ...

**Comment by DaneshX** [comment]
thanks i will try :)
